
services:
  mariadb:
    image: mariadb:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.mariadb
    restart: always
    environment:
      MYSQL_DATABASE: FitLife
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app-network
  python:
    image: python:3.9
    container_name: python
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    working_dir: /app
    networks:
      - app-network
    command: sh -c "pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
networks:
  app-network:
    driver: bridge

volumes:
  mariadbdata:
